### ISSUE TITLE
Brew canary build

### ISSUE THREAD

**Issue by OlshaMB** [raphamorim/rio#104]
- [x] canary tap
- [ ] discuss an idea where to put it and how to autoupdate it

**Comment by OlshaMB** [comment]
I made a canary tap:
https://github.com/OlshaMB/homebrew-rio

**Comment by raphamorim** [comment]
Hey @OlshaMB thank you for the tap 🙏 
Yesterday I've notarized the Application through Apple Developer program and sent an updated PR to Homebrew official repo with the notarized version https://github.com/Homebrew/homebrew-cask/pull/149824

For now I am closing this issue as I am expecting Rio to enter in the homebrew packages.

Thank you for the code reference ⭐

**Comment by OlshaMB** [comment]
Is homebrew cask gonna include a canary build?

**Comment by OlshaMB** [comment]
@raphamorim Is homebrew cask gonna include a canary build?

**Comment by OlshaMB** [comment]
I made this issue with canary build in mind

**Comment by raphamorim** [comment]
Haven't thought about canary versions with Homebrew to be honest, wonder if make sense to canaries have it. Considering also how to do it, because canaries versions are created in the GH pipeline but the plist is fixed with canary suffix (https://github.com/raphamorim/rio/blob/main/misc/osx/Rio.app/Contents/Info.plist#L23).

Looking forward to hear about your perspective regarding it. If the canaries become distributed by homebrew as a custom tap then make sense to have the formula in the repository.

**Comment by raphamorim** [comment]
> Looking forward to hear about your perspective regarding it. If the canaries become distributed by homebrew as a custom tap then make sense to have the formula in the repository.

If the canaries are distributed by Homebrew as custom tap then will have two Applications: "Rio" and "Rio Canary" which make sense, since is similar to how Chrome is distributed but is also different of the way that Rio releases have been going so far.

**Comment by raphamorim** [comment]
As an user @OlshaMB (also adding @avelino since he brought this up few weeks ago) would you prefer to have two Rio applications (stable and canary) or same application that can be stable/canary build
