### ISSUE TITLE
Rio cannot open files in the "folder" format.

### ISSUE THREAD

**Issue by moeyua** [raphamorim/rio#107]
Visual Studio Code external terminal support
<img width="479" alt="image" src="https://github.com/raphamorim/rio/assets/45156493/be624217-81d4-4901-aa55-280b344a24fe">
<img width="308" alt="image" src="https://github.com/raphamorim/rio/assets/45156493/b5ce5dfc-838f-4c38-86d6-74f34e799200">

**Comment by raphamorim** [comment]
Hey there @Moeyua , thank you for the issue! Was that working before? (wonder if it has anything with the changes I've made for Microsoft Windows support)

**Comment by Moeyua** [comment]
> Hey there @Moeyua , thank you for the issue! Was that working before? (wonder if it has anything with the changes I've made for Microsoft Windows support)

This issue has been present since I started using Rio on June 6th.

**Comment by Moeyua** [comment]
Furthermore, I am using macOS Ventura 13.4, the latest versions of Visual Studio Code - Insiders and Visual Studio Code.

**Comment by raphamorim** [comment]
Ah ok, that's good to know. Will look on it 👌 thanks for all the details

**Comment by raphamorim** [comment]
Figured out the reason.

Added the half of the support in fcb237fe167d61cd4d675d26309a5cc75f07e25c, it opens without alert but doesn't process the file path. The remaining part of the fix is to make Rio deal with the OpenFile events.

Will be looking on it for the next version (0.0.8)

References

- cocoa window https://github.com/page-down/kitty/blob/d19f28f2b4e5950bb5ab287280274bae129b30d2/kitty/cocoa_window.m#L545C9-L555
- https://github.com/rust-windowing/winit/pull/1759/files

**Comment by raphamorim** [comment]
Ref: https://github.com/rust-windowing/winit/issues/1751#issuecomment-1623169493

**Comment by Nyabinary** [comment]
cc @raphamorim You need to move this to 0.0.21 milestone I'm pretty sure.

**Comment by raphamorim** [comment]
Implemented in #461 

![rio-demo-open-file](https://github.com/raphamorim/rio/assets/3630346/9ac72832-f93a-4ffd-81a2-562640257ed6)

![rio-demo-open-folder](https://github.com/raphamorim/rio/assets/3630346/364f33fd-6413-4a05-acdd-4eba568e14f5)

Changes will be release along with 0.1.0 version
