### ISSUE TITLE
rio not setting correct terminal entry

### ISSUE THREAD

**Issue by Jinkxed** [raphamorim/rio#180]
I think this is what is causing all the keyboard issues when SSHing into other servers.

SSH into another server and run something like vim
`vim somefile`

```
E558: Terminal entry not found in terminfo
'rio' not known. Available builtin terminals are:
    builtin_ansi
    builtin_vt320
    builtin_vt52
    builtin_xterm
    builtin_iris-ansi
    builtin_pcansi
    builtin_win32
    builtin_amiga
    builtin_dumb
    builtin_debug
defaulting to 'ansi'
```

Setting: 
```
TERM=vt100
export TERM
```

Resolves a bunch of keyboard / terminal related issues.

**Comment by raphamorim** [comment]
This issue is the same as https://github.com/alacritty/alacritty/issues/3360

Basically the issue is that your remote server doesn't have `rio` terminfo, which is why you're seeing this error. So you should install `rio` terminfo on a remote server or use a different terminfo either in config or per connection with `env TERM=xterm-256color ssh` could work.

Also related https://serverfault.com/questions/1098644/alacritty-throws-e558-terminal-entry-not-found-in-terminfo-when-running-htop
