### ISSUE TITLE
Error with Synology and ssh

### ISSUE THREAD

**Issue by antoinecrouzet** [raphamorim/rio#216]
Hey,

in all the release, when we ssh in a Synology NAS (RS1221 but I test with others), there are several problems : 

- the backspace touch work but it'snt show (we don't see the character deleted effectively)
- when we vi, there is a message 

```
E558: Terminal entry not found in terminfo
'rio' not known. Available builtin terminals are:
    builtin_ansi
    builtin_xterm
    builtin_iris-ansi
    builtin_dumb
defaulting to 'ansi'
```

but vi is not properly working (up/down touch are not working, ...).

I'm not sure if it's only a rio problem or not. Any guess ?

**Comment by raphamorim** [comment]
Hey there @antoinecrouzet thanks for the issue,

Basically the issue is that your remote server doesn't have rio terminfo. Similar to this one https://github.com/raphamorim/rio/issues/180

So to fix it, you should install rio terminfo on a remote server or use a different terminfo either in config or per connection with `env TERM=xterm-256color ssh`.

**Comment by antoinecrouzet** [comment]
OK, it works... sorry for this :-)
