### ISSUE TITLE
[Feature Request] Built-In Themes in Rio

### ISSUE THREAD

**Issue by Nyabinary** [raphamorim/rio#253]
This would make it much simpler to do reproducible builds with NixOS, for example if Rio had built-in themes or if Rio automatically fetches the theme, download it, and apply it automatically.

**Comment by raphamorim** [comment]
I don't think Rio will have built-in themes, not that I am against it but is just the nature of the project now. Rio for example does not owns most of the packager manager content and I feel it is great, since everyone can package how they believe Rio should be (not being centralized) so they can pack/install the terminfo or not and it goes for themes as well.

I also considering in the future stop having built-in fonts and leave it to users / package-managers to deal with it, so is just how the nature of the project is (less centralized).

For nixos users, I do believe the best would be either have a list of themes installed along with the nixos package or have a package for rio terminal themes (as it has for terminfo). I will be closing this issue for now

**Comment by Nyabinary** [comment]
> I don't think Rio will have built-in themes, not that I am against it but is just the nature of the project now. Rio for example does not owns most of the packager manager content and I feel it is great, since everyone can package how they believe Rio should be (not being centralized) so they can pack/install the terminfo or not and it goes for themes as well.
> 
> I also considering in the future stop having built-in fonts and leave it to users / package-managers to deal with it, so is just how the nature of the project is (less centralized).
> 
> For nixos users, I do believe the best would be either have a list of themes installed along with the nixos package or have a package for rio terminal themes (as it has for terminfo). I will be closing this issue for now

Hmm, what about not having built in themes but creating a repo that has themes inside them, so Rio fetches the repo from that url automatically and installs it for you? Users can contribute to the repo, so all themes would be in one location instead of being spread out as well while still being pretty decentralized/up to the user control to make custom themes.

**Comment by raphamorim** [comment]
yea anything for retrieve it would work, would work in nixos do something like

```sh
curl https://raw.githubusercontent.com/user/repository/main/install.sh | bash
```

And basically move all installed themes to `~/.config/rio/themes`?

**Comment by otavio** [comment]
If themes must be available, it must be packaged as well.

**Comment by raphamorim** [comment]
Got the themes from https://github.com/mbadolato/iTerm2-Color-Schemes/ in https://github.com/raphamorim/rio-terminal-themes , feel free to use (port/fork) or anything else (I don't plan to actively maintain it, since my main focus is rio terminal)

**Comment by Nyabinary** [comment]
> If themes must be available, it must be packaged as well.

This wouldn't be necessary if Rio fetched and install the theme

**Comment by Nyabinary** [comment]
Updated the title and comment part of the issue @raphamorim, is it okay to reopen this or should I just make a new issue, I think we should keep it here since the comment history is here.
