### ISSUE TITLE
[Feature Request] Rio automatically fetches & installs theme from a settings-defined repo.

### ISSUE THREAD

**Issue by Nyabinary** [raphamorim/rio#274]
Rio automatically fetches the theme, download it, and applies/installs it automatically, this would make it much simpler to get new themes easily and preview themes as well. The default repo Rio fetches from will be: https://github.com/raphamorim/rio-terminal-themes, but users can manually define which repos to fetch from, and there could be even multiple repos a user can fetch from if possible.

Previous discussion on how this could be possibly implemented took place in #253

**Comment by raphamorim** [comment]
I don't see this being implemented on Rio for now, I do think themes should be obtained either

1. individual download of the theme by the user (like https://github.com/dracula/rio-terminal)
2. distribution of a packaged collection of themes through package managers
3. download support (as this issue described) however using plugin system

Rio doesn't have plugin system right now (ref #176) so even that if want to start doing that right now wouldn't be possible, but don't want to add/teach Rio how to make requests neither control themes, I do believe it should be part of the plugins system to don't interfere for users that don't use this feature.

I will be closing this issue for now, since I don't intent to add this to Rio as a built-in support
