### ISSUE TITLE
Font ligatures feature is missing from the feature list

### ISSUE THREAD

**Issue by karesztrk** [raphamorim/rio#292]
I noticed that the Font Ligature support disappeared from the documentation completely.
Was it an intended change? Will you put it back eventually?

**Comment by raphamorim** [comment]
Hey @karesztrk thanks for the issue, it is in the wishlist. Originally was coming for 0.0.22 but I wasn't satisfied with the performance of the implementation and dropped it from release.

There's an issue regarding ligatures #108 , hopefully tweak on it for the feature but one of my personal requirements for achieve this feature is not affect the performance for users that doesn't use font ligatures.

Will be closing this issue since #108 is the one to track.
