### ISSUE TITLE
rio could use a cool logo

### ISSUE THREAD

**Issue by jeremiah** [raphamorim/rio#299]
Branding is an important part of successful open source projects. :-)

**Comment by raphamorim** [comment]
I assume that you don't like the current one.

<img width="542" alt="Screenshot 2023-10-19 at 22 07 08" src="https://github.com/raphamorim/rio/assets/3630346/b9e81196-8460-4741-8f24-751b4d9557d0">

Open any for suggestions, feel free to contribute I am always keen to see ideas and discuss, if it does looks better then I am super keen in switch for what we have today. However the change isn't come from my side since it has just switched for the image one few version ago.

Closing this issue since isn't really an issue but feel free to convert to a GH discussion.

**Comment by jeremiah** [comment]
Sorry, I _do_ like it. For some reason it doesn't show up on my system (Debian / Wayland / GNOME). I'll see if I can fix that. :-)
