### ISSUE TITLE
rio themes docs should describe the three color sets

### ISSUE THREAD

**Issue by colemickens** [raphamorim/rio#337]
My Rio looks slightly different than Alacritty/wezterm even when configured with the same colors. I suspect this is because I didn't override the dimmed color set.

Why does Rio have three sets when every other emulator has two?

**Comment by raphamorim** [comment]
Hey @colemickens thanks for the issue,

Rio does have the three colors sets in the docs no?

<img width="353" alt="Screenshot 2023-11-14 at 10 19 07" src="https://github.com/raphamorim/rio/assets/3630346/a52533f7-3b9c-4ccb-a791-2fecf9f5517c">

Other terminals use algorithms to find the dimmed color version while rio doesn't allow that (i think it could be a configurable thing) because often saw issues with people complaining the dimmed version, rather give this power to the person using the terminal.

Closing this issue for now, but might be a good opportunity to open another issue regarding add algorithm to find the dimmed version.
