### ISSUE TITLE
Core dump unless on GPU / XScreen 0.0

### ISSUE THREAD

**Issue by nPHYN1T3** [raphamorim/rio#360]
rio 0.0.28-1
thread 'main' panicked at frontends/cross-winit/src/router/mod.rs:321:61:
called `Result::unwrap()` on an `Err` value: OsError { line: 332, file: "/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.4/src/platform_impl/linux/x11/window.rs", error: XError(X11(X11Error { error_kind: Match, error_code: 8, sequence: 189, bad_value: 902, minor_opcode: 0, major_opcode: 1, extension_name: None, request_name: Some("CreateWindow") })) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

I suppose another way of saying this is you can't choose which GPU to run it on heh. Even better if it didn't lock on to ONE GPU and just chose acceleration from the GPU running the XScreen it was launched on.

Normally (sadly) GPU accelerated things can only be run on whichever GPU the initial instance was launched on but with rio it ignores the GPU it's being launched on and just locks on to first enumerated?, GPU running the assumed default XScreen 0.0?, PCIe / bus order? (you tell me ;p)

**Comment by raphamorim** [comment]
Yes, Rio doesn't consider the GPU it was launched (as other software does as well). Rio relies on WGPU driver selection (which didn't work correct for your case) but maybe a good idea is to allow select drivers per configuration.

**Comment by raphamorim** [comment]
> Driver selection would be a bad way to go about it given all my GPU's run the same driver ;)

But your case is one case, no? The driver selection doesn't even happen in Rio source code but in the wgpu that finds the best adapter per drive to run the terminal (which isn't always the driver in use). I could manually though specify the driver but I don't want to that for all cases, this would imply that everyone knows how a driver/adapter relationship work which isn't the case. Considering that, I would rather add an option that you could specify the driver instead of assume the running driver is the best to use, because isn't always like this.

**Comment by raphamorim** [comment]
Anyhoo will close it for now since I have no plans in revisit driver selection for now (at least not until after February with new wgpu release)
