### ISSUE TITLE
Tabs navigation key bindings do not work

### ISSUE THREAD

**Issue by iblazhko** [raphamorim/rio#402]
According to https://raphamorim.io/rio/docs/key-bindings#linux-and-bsd

`Control+Shift+,` should open configuration, `Control+Shift+[` / `Control+Shift+]` should navigate between tabs.

these keybindings do not work for me - nothing happens, and Rio does not print any characters (like with other unbound combinations, e.g. `Control+Shift+?` - it prints `?` in this case).

`Control+Shift+T` (new tab), `Control+Shift+N` (new window) work OK, so it is not that everything is broken.

As far as I can see no application-specific or system-wide keybindings for `Control+Shift+,`, `Control+Shift+[`, `Control+Shift+]`, but TBH I am not 100% sure, is there a way to check it?

Rio does not complain about keybindings in debug output (`[developer] log-level = "DEBUG"`).

When I press `Control+Shift+[`, `Control+Shift+]`, there is following debug output:

```
[DEBUG] wgpu_core::device::resource Create view for texture Id { index: 2, epoch: 115, backend: Vulkan } filters usages to TextureUses(COLOR_TARGET)
[DEBUG] wgpu_core::device::life Texture view Valid(Id { index: 3, epoch: 57, backend: Vulkan }) will be destroyed
[DEBUG] wgpu_core::present Removing swapchain texture Valid(Id { index: 2, epoch: 115, backend: Vulkan }) from the device tracker
[DEBUG] wgpu_core::present Presented. End of Frame
```

but active tab does not change.

* * *

* OS: Pop!_OS 22.04 LTS with all updates applied at the moment of writing
* Windowing System: X11  
* Rio: `rioterm 0.0.33`
  * (built from sources using `cargo 1.75.0`)

**Comment by hougesen** [comment]
I believe this might be related to your keyboard layout.

The keybinds does not work for me either, but it does after changing the following lines to new keys.

https://github.com/raphamorim/rio/blob/44532fac8cac8b0079bda72464d7b9e83d920f60/frontends/cross-winit/src/screen/bindings/mod.rs#L1038-L1039

`[` and `]` does not have dedicated keys on my keyboard (Danish, Ubuntu 23.10). To make a `[` I need to press `Alt + 8`, which of course results in a different sequence (`Ctrl + Shift + Alt + 8`).

The fastest solution is to create a [custom key binding](https://raphamorim.io/rio/docs/key-bindings#custom-key-bindings).

**Comment by iblazhko** [comment]
My keyboard is a standard ANSI US layout.

I think the problem is related to how keypresses are reported to the application, and it may not be specific to the Rio / rust. I am not familiar with this area, and don't really want to go down this rabbit hole, but I did a quick test using [screenkey](https://www.thregr.org/~wavexx/software/screenkey/):

https://github.com/raphamorim/rio/assets/87576/2fd60932-c41a-4f96-9d9b-98f024282b33

What I see is that reported keypresses are `Ctrl+{` / `Ctrl+}` and not `Ctrl+Shift+[` / `Ctrl+Shift+]`, this kind of makes sense if we consider key _press_, not key _down_.

Interestingly, while screenkey shows `Ctrl+{` / `Ctrl+}`, terminal prints `^[` / `^]` :shrug:.

Anyway, following custom key bindings work for me:

```toml
[bindings]
keys = [
  { key = "{", with = "control | shift", action = "SelectPrevTab" },
  { key = "}", with = "control | shift", action = "SelectNextTab" }
]
```

maybe worth adding this into the code linked above.

**Comment by raphamorim** [comment]
Very interesting, 

> [ and ] does not have dedicated keys on my keyboard (Danish, Ubuntu 23.10). To make a [ I need to press Alt + 8, which of course results in a different sequence - Ctrl + Shift + Alt + 8 (Unless I am pressing the wrong keys 😅 ).

Maybe would be worthy to update to `}` and `{` instead on linux. @hougesen @iblazhko would anyone would like to make a PR?

**Comment by raphamorim** [comment]
Probably remove tab navigation default option might be the best option, so wouldn't break for the opposite cases and then we can highligh how to do it in the docs.

**Comment by hougesen** [comment]
> Maybe would be worthy to update to `}` and `{` instead on linux. ...

I prefer using `Ctrl + Tab` for switching (and I am guessing most do?) so the change would have no effect on me.

I did a quick dive into terminal emulators, and was able to find a couple that support `Ctrl + Shift + SquareBracket` (Among them is [Kitty](https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Next-window)). I was not able to find a single one that uses `Ctrl + Shift + Curly`.

Using the same keybinds as other terminals is in my opinion the better choice since it lowers the barrier of entry for new users, but I have no "skin in the game" so feel free to disregard my opinion 😄

Since rio supports custom keybinds the user is able to change it to their preferred keys no matter what.

>  I think the problem is related to how keypresses are reported to the application, and it may not be specific to the Rio / rust.

I believe the best option is to figure out the above. Since Kitty uses the same keybind it sounds like a rio issue (or winit?). Sadly I am not able to look into it, since my keyboard layout is different 😅

The [following section](https://raphamorim.io/rio/docs/key-bindings#linux-and-bsd) in the docs might be a good idea to clarify. As far as I can tell `Ctrl + Tab` is the same as `Ctrl + Shift ]` and `Ctrl + Shift + Tab` equals `Ctrl + Shift + [`. 

![image](https://github.com/raphamorim/rio/assets/56034786/fc753441-9212-40d1-aab3-ff851a8ded0f)

**Comment by raphamorim** [comment]
Thanks for the PR @hougesen, Will be closing this issue for now but let me know anything
