### ISSUE TITLE
deb has the same name as an existing package

### ISSUE THREAD

**Issue by toneman77** [raphamorim/rio#425]
Tried rio, liked it a lot, but after i ran my usual daily update/upgrade it disappeared. After some research I found out that on my ubuntu machine rio got upgraded to 1.07 from the official repos. But that is a tool for controlling a Diamond RIO mp3 player.

Would it be possible to rename the package that gets generated in the release to be renamed to rio-terminal or something like that, so that it wont conflict with an already existing package name in ubuntu?

what already exists:
```
rio 1.07-14ubuntu1 [Ubuntu/jammy universe]
  Command line Diamond Rio MP3 player controller
```

**Comment by raphamorim** [comment]
Hey there @toneman77, thanks for the issue!

How do you build/get Rio binary? Often the package managers dictate the name for the binary be `rio` is just a suggestion but in multiple OS have been named with different names like `rioterm` (crates.io for example), `rio-terminal`, `rio-term` (...)

**Comment by toneman77** [comment]
I downloaded and installed the deb file from here: https://github.com/raphamorim/rio/releases 
I assume it get generated somewhere in the official build process?

**Comment by raphamorim** [comment]
Yes, it does build on gh pipeline but frankly is a bit tricky to maintain the current GH release pipeline for linux because since it only have deb architecture=amd64 there. I have been thinking about actually rely more on package managers releases than the GH pipeline to distribute linux, due to multiple reasons like different OS packager managers have different naming for the rio terminal binary (for example MacOS is `rio`) and it's quite tricky to what Mitchell also mentioned https://twitter.com/mitchellh/status/1750942357510627605 , plan to add/maintain different linux binary builds in one repo have been a pain 😓 .

For now I will close this issue because I have no interest in maintain the GH distribution for linux (at least for now), however if someone would like to help in create a decent matrix of releases for linux like kitty I am up to help in any level.

@toneman77 other suggestion would be install from `cargo` https://crates.io/crates/rioterm , it's named as `rioterm` there. In other note would be awesome if rio could be ported officially to deb packages with `rioterm` naming.
