### ISSUE TITLE
Is debian `.deb` not supported or we forgot to update the docs?

### ISSUE THREAD

**Issue by AucaCoyan** [raphamorim/rio#452]
Hi! Fellow rustacean here, but from the debian distro.
I found that [the installation methods on linux](https://raphamorim.io/rio/docs/install/linux) don't include debian distros, but `.deb` is generated in the releases.

Should we update the docs then?

**Comment by raphamorim** [comment]
Hey @AucaCoyan thank you for the issue and sorry by delay!

Yea, this is a great question tbh. Currently `.deb` is generated in the releases but is only for `amd64`, so the infra for delivery binaries through releases is quite poor. Which would leave to few possibilities:

- Ideally the best case scenario would be Rio be distributed through package managers as arch, alpine and etc. This helps me a lot to focus mostly on the terminal code which is already a good part of my time on Rio.
- Could add the binaries targets on GH pipeline but I am not sure if I want to put effort in add all binary target on GH releases mostly because of maintenance. In the future ~maybe~ could be definitely an option but currently I have working most on the new text renderer/split features and a replace for winit, so is hard to guess when I would start it.
- Other possibility is to mention that rio does have a command to build `deb` in the docs.

I am closing this issue for now but we can keep the discussion 👌
