### ISSUE TITLE
rio is another known name for ages...

### ISSUE THREAD

**Issue by OrionRandD** [raphamorim/rio#47]
Hi,

rio is the window manager of plan9 and 9front for ages now...
it will make confusion on github... LOL
http://www.9front.org/releases/
https://plan9.io/plan9/

**Comment by raphamorim** [comment]
Hey there,
Yes, it was something I knew before but isn't a concern now how Rio will be distributed besides macos. Alternatively, can always serve the application/binary for specific platforms with different names, an example would be add the suffix "term", as `rioterm`.

I am closing this issue for now, since isn't a major concern for upcoming releases (MacOS and WASM).

**Comment by Humm42** [comment]
It truly is a little unfortunate, not only because rio is Plan 9’s device multiplexer, but also because rio can run as X11 window manager on Unix-like systems as part of plan9port.

**Comment by Humm42** [comment]
Oh, and the name “rio” is also used by [RasterIO](https://rasterio.readthedocs.io/en/latest/cli.html).
