### ISSUE TITLE
Macos Ventura: Says the binary is damaged

### ISSUE THREAD

**Issue by raguay** [raphamorim/rio#49]
I can't run the latest version due to the macos saying it is damaged. I'm on a macbook pro m1 chip system.

**Comment by raphamorim** [comment]
Hey there @raguay , the issue root cause is because the application is not notarized yet, so is necessary to run a command on the app file before try to open. Follow the steps of the docs or in case need more info, there's some links regarding this problem in the #41 

https://raphamorim.io/rio/download/

<img width="1050" alt="Screenshot 2023-05-25 at 06 50 21" src="https://github.com/raphamorim/rio/assets/3630346/d5a01382-87ef-4290-9c07-12d844f9f9e0">

**Comment by raguay** [comment]
Okay. That worked. I use notarized apps a lot and they usually show up in the security section to allow it to run. Usually, I only get the binary is damaged when it actually is.

**Comment by raphamorim** [comment]
Yea, isn't the best approach now to run it. I hope to get Rio app notarized in the upcoming weeks so we can avoid this type of issues. Anyway, thank you for reporting as well.

**Comment by raphamorim** [comment]
For reference, notarized the application. Adding it to homebrew https://github.com/Homebrew/homebrew-cask/pull/149824
