### ISSUE TITLE
"confirm-before-quit" doesn't work

### ISSUE THREAD

**Issue by LearnWebGitHub** [raphamorim/rio#602]
Rio would exit immediately without confirming even there's command running
I've tried it on weston, i3 and sway

**Comment by orhun** [comment]
I'm on i3 as well and I'm not sure how you expect Rio to confirm for exit since the default window kill command (`$mod+Shift+q`) simply sends the kill signal to the application. I'm guessing it is the equivalent of `kill -9 $(pgrep rio)`.

Even though Rio can catch this signal, it might not be actionable since the application is already killed. Maybe it is supposed to act upon "window close" signal which is also not actionable on `i3` (tried it with `xdotool windowclose`). 

I'm not sure how this feature is expected to work (or how does it work on other platforms) so maybe @raphamorim can enlighten us about it.

**Comment by raphamorim** [comment]
I think I broke this feature when went from 0.0.x to 0.1.0 tbh. Back in the old versions would appear a screen in the last window or every time triggered close button/shortcut in the window.

the screen would ask, press enter to confirm

**Comment by LearnWebGitHub** [comment]
OK, thanks for the answer!

**Comment by orhun** [comment]
let's keep this open, I will give it a shot fixing it

**Comment by raphamorim** [comment]
0.0.38 still works, the 0.1.8 is broken though

![image](https://github.com/user-attachments/assets/165227b3-9d03-4516-b23b-92b5c1454caa)

**Comment by orhun** [comment]
I still don't get that page on i3 even with the suggested version. Like I said, it is probably because i3 simply kills the window instead of closing it due to the fact that there is no "close button". It is a tiling window manager afterall.

Either way, I will find a way to trigger that screen and potentially fix it for other desktop environments.

**Comment by orhun** [comment]
I also tried the native "Rio way" of closing it via following custom key binding:

```toml
[bindings]
keys = [
  { key = "home", action = "Quit" },
]
```

Neither it quit when I press home (or any other configured key) nor I got a confirmation screen.

Am I doing something wrong here? @raphamorim

**Comment by raphamorim** [comment]
Quit is triggered by key bindings, on macos would be `Command + Q` and in that case would confirm-before-quit.

Exit is when rio just shuts down and it can happen for many reasons, like kill the process even.

**Comment by orhun** [comment]
Unfortunately I can't trigger it on i3 even with the older versions which makes me further believe that it is not actually possible...

**Comment by LearnWebGitHub** [comment]
When I was using GNOME Terminal, I can trigger this on i3 (mod+shift+q).
So I think it's possible although I have absolutely no idea how to implement it.

**Comment by jessejoe** [comment]
I just installed on macOS and noticed neither confirm to quit, nor remapping Cmd-Q to "none" work:
```
keys = [
   { key = "q", with = "super", action = "none" }
]
```

It's definitely possible because iTerm 2 has a confirm on quit, as does Firefox.

**Comment by raphamorim** [comment]
yes, it is possible, it used to work entirelly on macos at least but is broken now 😢 
will take a look on it this week as well

**Comment by raphamorim** [comment]
I made the proper fix for MacOS on 0.1.16 (using native resources)

![image](https://github.com/user-attachments/assets/c83c8977-0338-4088-ab18-81679d3413fd)

I plan to iterate fixes for Windows/Linux next versions

**Comment by LearnWebGitHub** [comment]
Nice! Looking forward to the next version.

**Comment by raphamorim** [comment]
Should be fixed on main right now, asked some peeps to test windows and linux they reported it's working now.

Please lemme know if doesn't then i can reopen
