### ISSUE TITLE
Multi window support

### ISSUE THREAD

**Issue by OlshaMB** [raphamorim/rio#97]
Support for multiple windows

**Comment by raphamorim** [comment]
Hey @OlshaMB thanks for bringing this up, I will probably visit this issue for the 0.0.8 version (after the next release) 👌

**Comment by lucasew** [comment]
On Linux, it works with multi windows, like I can open more than one rio window.

Do you mean tabs? Why not use a multiplexer such as tmux?

**Comment by OlshaMB** [comment]
**Works on Linux**
Maybe i3 or your compositor just creates new instance.
**Why not use tmux**
Because I use a tiling macOS window manager and I don't need tmux to tile my terminal windows, and if I want to tile any other window I want to do it with same keybind

**Comment by raphamorim** [comment]
Yea, I know is possible for linux (wayland and x11) but for macos we don't have an UI control like this:

<img width="290" alt="Screenshot 2023-06-19 at 10 51 10" src="https://github.com/raphamorim/rio/assets/3630346/dd122ee6-604f-426f-8725-54ea9a7b57c8">

The way NixOS distributes, basically you can trigger as many rio instances you want to. For MacOs is also possible but would require map rio binary to shells, in terms of UI we don't have anything. Believe this issue is more MacOS based.

**Comment by raphamorim** [comment]
Multiwindow introduced in https://github.com/raphamorim/rio/commit/cbbe503c917f555c590434280567c81089c6cd8f

![Screenshot 2023-07-09 at 10 58 54](https://github.com/raphamorim/rio/assets/3630346/fb908cd3-0c4e-457e-b289-28bf0e66d69b)
